starwars/routes/pages.py
"""Pages routes."""
import logging

from typing import Optional

import flask

from flask import Blueprint
from flask import make_response
from flask import render_template
from marshmallow import EXCLUDE
from webargs.flaskparser import parser

from starwars.business import auth
from starwars.business import retrieve_page_from_persons
from starwars.business import retrieve_starships_rated
from starwars.schemas.person_routes import RetrievePersonsSchema
from starwars.services.db import DBFilter
from starwars.services.db.film import get_film
from starwars.services.db.film import get_films
from starwars.services.db.planet import get_planet
from starwars.services.db.planet import get_planets
from starwars.services.db.specie import get_specie
from starwars.services.db.starship import get_starship
from starwars.services.db.vehicle import get_vehicle
from starwars.services.db.vehicle import get_vehicles
from starwars.support.pagination_utils import get_max_pages_from_sequence_length

logger = logging.getLogger(__name__)

blueprint = Blueprint("pages_routes", __name__)


@blueprint.route("/")
def index() -> flask.Response:
    """Retrieve the index page."""
    return make_response(render_template("index.html"), 200)


@blueprint.route("/healthcheck/")
def healthcheck() -> flask.Response:
    """Retrieve the healthcheck page."""
    return make_response(render_template("healthcheck.html"), 200)


@blueprint.route("/persons/", methods=("GET", "POST"))
@parser.use_kwargs(RetrievePersonsSchema(unknown=EXCLUDE), location="form")
@auth.login_required
def persons(
    page: int,
    sort_by: str,
    sort_order: str,
    film: Optional[int] = None,
    vehicle: Optional[int] = None,
    planet: Optional[int] = None,
    starship: Optional[int] = None,
) -> flask.Response:
    """Retrieve the persons page."""
    logger.info(
        "Loading persons page with the following params: page - %s, sort_by - %s, sort_order - %s, film - %s, "
        "vehicle - %s, planet - %s, starship - %s",
        page,
        sort_by,
        sort_order,
        film,
        vehicle,
        planet,
        starship,
    )

    filters = [
        filter_option
        for filter_option in [
            DBFilter(table="person", field="homeworld", value=planet),
            DBFilter(table="film_character", field="film_id", value=film),
            DBFilter(table="vehicle_pilot", field="vehicle_id", value=vehicle),
            DBFilter(table="starship_pilot", field="starship_id", value=starship),
        ]
        if filter_option.value
    ]

    result = retrieve_page_from_persons(page, sort_by, sort_order=sort_order, filters=filters)
    persons = []
    for person in result["items"]:
        person["homeworld"] = (
            get_planet(planet_id=person["homeworld"])["name"] if person["homeworld"] else person["homeworld"]
        )
        person["films"] = ", ".join(get_film(film)["title"] for film in person["films"]) if person["films"] else ""
        person["species"] = (
            ", ".join(get_specie(specie)["name"] for specie in person["species"]) if person["species"] else ""
        )
        person["starships"] = (
            ", ".join(get_starship(starship)["name"] for starship in person["starships"]) if person["starships"] else ""
        )
        person["vehicles"] = (
            ", ".join(get_vehicle(vehicle)["name"] for vehicle in person["vehicles"]) if person["vehicles"] else ""
        )
        persons.append(person)

    starships, films, planets, vehicles = retrieve_starships_rated(), get_films(), get_planets(), get_vehicles()

    return make_response(
        render_template(
            "persons.html",
            persons=persons,
            starships=starships,
            films=films,
            planets=planets,
            vehicles=vehicles,
            max_pages=get_max_pages_from_sequence_length(result["total"]),
            current_page=page,
            sort_by=sort_by,
            selected_planet=planet,
            selected_film=film,
            selected_vehicle=vehicle,
            selected_starship=starship,
            sort_order=sort_order,
        ),
        200,
    )


@blueprint.route("/starships/")
@auth.login_required
def starships() -> flask.Response:
    """Retrieve the starships page."""
    logger.info("Loading starships page")
    starships = retrieve_starships_rated()
    return make_response(render_template("starships.html", starships=starships), 200)

starwars/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - SenseData - Code Challenge</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1><a href="{{ url_for('pages_routes.index') }}">SenseData - Code Challenge</a></h1>
  <ul>
    <li><a href="{{ url_for('pages_routes.healthcheck') }}">Healthcheck</a>
    <li><a href="{{ url_for('pages_routes.persons') }}">Persons</a>
    <li><a href="{{ url_for('pages_routes.starships') }}">Starships</a>
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% block content %}{% endblock %}
</section>

starwars/templates/healthcheck.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Healthcheck{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="content">
    No service is actually been checked, yet!
</div>
{% endblock %}

starwars/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>What is this app?</h1>
<div class="content">
    A Flask APP that returns information from the Star Wars franchise.
</div>
<h1>What can I do?</h1>
<div class="content">
    You can check information from <a href="{{ url_for('pages_routes.persons') }}">characters</a> and <a href="{{ url_for('pages_routes.starships') }}">starships</a>
</div>
{% endblock %}

starwars/templates/persons.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Persons{% endblock %}</h1>
{% endblock %}

{% block content %}
<div>
    <div style="width: 75%;">
        <form method="post">
            <label for="sort_by">Sort options</label>
            {% for sort_option, sort_label in {"name": "Name", "gender": "Gender", "mass": "Weight", "height": "Height"}.items() %}
            <label for="{{ sort_option }}">
                {% if sort_by == sort_option %}
                <input type="radio" id="{{ sort_option }}" name="sort_by" value="{{ sort_option }}" checked>
                {% else %}
                <input type="radio" id="{{ sort_option }}" name="sort_by" value="{{ sort_option }}">
                {% endif %}
                {{ sort_label }}
            </label>
            {% endfor %}

            <br>

            <label for="sort_order">Sort order</label>
            {% for order_option, order_label in {"ASC": "Ascending", "DESC": "Descending"}.items() %}
            <label for="{{ order_option }}">
                {% if sort_order == order_option %}
                <input type="radio" id="{{ order_option }}" name="sort_order" value="{{ order_option }}" checked>
                {% else %}
                <input type="radio" id="{{ order_option }}" name="sort_order" value="{{ order_option }}">
                {% endif %}
                {{ order_label }}
            </label>
            {% endfor %}

            <br>

            <label for="filters">Filter options</label>

            <br>

            <label for="film">Film</label>
            <select id="film" name="film">
                {% if not selected_film %}
                <option value="" selected></option>
                {% else %}
                <option value=""></option>
                {% endif %}
                {% for film in films %}
                    {% if film["id"] == selected_film %}
                    <option value="{{ film['id'] }}" selected>{{ film["title"] }}</option>
                    {% else %}
                    <option value="{{ film['id'] }}">{{ film["title"] }}</option>
                    {% endif %}
                {% endfor %}
            </select>

            <label for="starship">Starship</label>
            <select id="starship" name="starship">
                {% if not selected_starship %}
                <option value="" selected></option>
                {% else %}
                <option value=""></option>
                {% endif %}
                {% for starship in starships %}
                    {% if starship["id"] == selected_starship %}
                    <option value="{{ starship['id'] }}" selected>{{ starship["name"] }}</option>
                    {% else %}
                    <option value="{{ starship['id'] }}">{{ starship["name"] }}</option>
                    {% endif %}
                {% endfor %}
            </select>

            <br>

            <label for="vehicle">Vehicle</label>
            <select id="vehicle" name="vehicle">
                {% if not selected_vehicle %}
                <option value="" selected></option>
                {% else %}
                <option value=""></option>
                {% endif %}
                {% for vehicle in vehicles %}
                    {% if vehicle["id"] == selected_vehicle %}
                    <option value="{{ vehicle['id'] }}" selected>{{ vehicle["name"] }}</option>
                    {% else %}
                    <option value="{{ vehicle['id'] }}">{{ vehicle["name"] }}</option>
                    {% endif %}
                {% endfor %}
            </select>

            <label for="planet">Planet</label>
            <select id="planet" name="planet">
                {% if not selected_planet %}
                <option value="" selected></option>
                {% else %}
                <option value=""></option>
                {% endif %}
                {% for planet in planets %}
                    {% if planet["id"] == selected_planet %}
                    <option value="{{ planet['id'] }}" selected>{{ planet["name"] }}</option>
                    {% else %}
                    <option value="{{ planet['id'] }}">{{ planet["name"] }}</option>
                    {% endif %}
                {% endfor %}
            </select>

            <br>

            {% if max_pages > 0 %}
            <label for="page">
                Which page?
                <input id="page" type="number" name="page" min="1" max="{{ max_pages }}" value="{{ current_page }}">
                / {{ max_pages }}
            </label>
            {% endif %}

            <input type="submit" value="Submit">
        </form>
    </div>
</div>
<div style="overflow-x: scroll;">
  <table id="person">
      <thead>
          {% if persons %}
              <tr>
                 {% for key in persons[0] %}
                     <th> {{ key }} </th>
                 {% endfor %}
              </tr>
          {% endif %}
      </thead>

      <tbody>
          {% for person in persons %}
          <tr>
             {% for value in person.values() %}
             <td> {{ value }} </td>
             {% endfor %}
          </tr>
          {% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}

starwars/templates/starships.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}Starships{% endblock %}</h1>
{% endblock %}

{% block content %}
<div style="overflow-x: scroll;">
    <table id="starship">
      <thead>
          {% if starships %}
              <tr>
                 {% for key in starships[0] %}
                 <th> {{ key }} </th>
                 {% endfor %}
              </tr>
          {% endif %}
      </thead>

      <tbody>
          {% for starship in starships %}
          <tr>
             {% for value in starship.values() %}
             <td> {{ value }} </td>
             {% endfor %}
          </tr>
          {% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}